### ISSUE TITLE
Take a look at Storybook

### ISSUE THREAD

**Issue by beriniwlew** [Vertical-OSS/networked-community#30]
@Vertical-OSS/creative-team 

Please take a look at StoryBook, and let me know what you think. 

https://storybook.js.org/

**Comment by marvinroman** [comment]
It’s cool. It seems to have a narrow use case for interactive trainings. If that the purpose it’s worth exploring. Outside of online books or training or docs I don’t see other use cases.
I also ran into a lot of bugs when viewing their demos. Their React one didn’t load properly the first time and required a page reload. Several components didn’t do what they said they would do like change background color. It may be browser compatibility, but seems likes it’s not mature if that’s the case.

**Comment by beriniwlew** [comment]
@huiqingao 

Wondering if this may be useful for you.

**Comment by beriniwlew** [comment]
We may reopen this later, then.
